### ISSUE TITLE
RSA KeyGen and self-signed X.509 on MacOS

### ISSUE THREAD

**Issue by xuganyu96** [tomato42/marvin-toolkit#10]
`certgen/cergen/lib.sh` seems to not work on MacOS. While trying to replicate this analysis on MacOS I used `openssl` to generate the RSA private keys and self-signed X.509 certificate. After that `step2.sh` and the test harness for Rust seem to work just fine:

```bash
for size in 1024 2048 4096; do
    mkdir -p rsa${size}

    # OpenSSL defaults to PKCS#8 so there is no need for conversion
    openssl genpkey \
        -algorithm RSA \
        -pkeyopt rsa_keygen_bits:${size} \
        -out rsa${size}/key.pem

    openssl req -new -key rsa${size}/key.pem -out rsa${size}/csr.pem

    openssl x509 -req \
        -days 365 \
        -in rsa${size}/csr.pem \
        -signkey rsa${size}/key.pem \
        -out rsa${size}/cert.pem
done
```

Would it be appropriate to add a bash script `step1-manual.sh` that doesn't depend on `certgen/lib.sh`?

**Comment by tomato42** [comment]
certgen requires real bash (it can be ancient one, like from RHEL-6, but it has to be bash), and the script requires relatively new openssl, so you need to have both installed from homebrew, not the Apple provided ones

the problem with this simple script is that it also provides just one format of the key, `step1.sh` provides 5...

So either it would have to be documented rather well, or extended quite a bit — other than that I have nothing against including it

**Comment by xuganyu96** [comment]
Thank you for the details. I tried running the analysis on a Debian container and `certgen` works just fine.
